### ISSUE TITLE
Vagner - `transferAllTokens` can be used by anyone to steal all of the funds in the `BasePositionManager.sol` and `AntiSnipAttackPositionManager.sol`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-kyber-swap-judging#33]
Vagner

high

# `transferAllTokens` can be used by anyone to steal all of the funds in the `BasePositionManager.sol` and `AntiSnipAttackPositionManager.sol`
## Summary
`transferAllTokens` is used to transfer all the tokens from the `BasePositionManager.sol` and `AntiSnipAttackPositionManager.sol` to the `recipient` , but that function doesn't have any modifier or protection and can be called by anyone and front-ran to steal funds from the contracts.
## Vulnerability Detail
`BasePositionManager.sol` and `AntiSnipAttackPositionManager.sol` is very similar to `NonfungiblePositionManager.sol` from UniswapV3 and acts as a manger where users can mint ERC721 and provide liquidity to pools, earning fees. The big difference between these two is that , the fees earned in Kyber-Swap protocol are earned in form of `RTokens` which can be burned to gain the actual tokens present in the pools. In UniswapV3 you can call `collect` to get transferred directly from the pools, all of the fees earned, but in Kyber-Swap you need to call `burnRTokens` which will transfer the fees earned from the pools to the `BasePositionManager.sol` / `AntiSnipAttackPositionManager.sol` itself, as can be seen here 
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L289-L290
which will make the fees be in those two contracts. After that if the user wants to actually get his fees earned by his position, he need to call `transferAllTokens` with those two tokens that were transferred from the pools.
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/periphery/BasePositionManager.sol#L298-L305
which will basically transfer the whole balance of those tokens in the contract 
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/periphery/base/RouterTokenHelper.sol#L32-L43
Because of that, anyone can front-run and steal all of the rewards from any user, the only possible way of protecting yourself is by using the `Multicall.sol` contract used, and batch multiple transactions into one, but that it is not a reliable protections against front-run, especially for normal users.
## Impact
Impact is a high one, because funds can be lost
## Code Snippet
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/periphery/BasePositionManager.sol#L298-L305
## Tool used

Manual Review

## Recommendation
Consider transferring directly the fees to the user after you burn the RTokens, keeping the fees in the managers contract and letting everyone to transfer funds from those contracts can be very dangerous in the long run, even one mistake can hurt the users.

**Comment by VagnerAndrei26** [comment]
Escalate
I want to escalate my issue to explain a bit better what I intended in my report. I am not arguing about the fact if that's the design of the protocol or not, I'm arguing the design itself since it can be easily abusable by experienced MEV/sniping bots users. The way the protocol is designed right now is forcing the users to make multiple transactions to burn the tokens and collect the rewards they earned. Let me give some more in-depth explanation about it. 
Providing liquidity and minting a new position, can be done trough a smart-contract or an EOA account so let's take both situations and see what is happening : 
- if we consider a smart-contract, the flaw that I presented can be easily avoided by calling both `burnRTokens` and `transferAllTokens` in the same function, which will transfer the specific `token0` and `token1` right away, in this situation no front-run or sandwich attack happen since the funds transferred in only one transaction
- if we consider an EOA account, especially one that interacts with the front-end of the project this is not the same, since they are forced to do at least 2 different transactions , one where he will burn their RTokens and one where he will transfer his rewards collected. That is very dangerous in general because any experienced MEV/sniping bot user can look especially for these cases and put their transactions, where they call `transferAllTokens` for themselves, right after the `burnRTokens` and before the `transferAllTokens` of the user. In UniswapV3, since kyber-swap implements a lot of logic from UniswapV3, this problem does not exist since the rewards are always stored into variables until the rightful owner calls `collect`.

As the judge said `BasePositionManager.sol` it is not intended to hold funds, but it will hold funds because of the way it is implemented, even if it is for few seconds/minutes, and because of that normal users could suffer loss of funds without having the ability to do anything, even if they call `transferAllTokens` right after burning their `RTokens`. Saying all of this I believe that the way the logic is implemented right now it is very disadvantageous for normal EOA users that are going to interact with the protocol and can lead to the loss of funds in a very easy manner since front-runs and sandwich attacks can be easily doable, especially when there is a lot to profit from.

**Comment by sherlock-admin2** [comment]
> Escalate
> I want to escalate my issue to explain a bit better what I intended in my report. I am not arguing about the fact if that's the design of the protocol or not, I'm arguing the design itself since it can be easily abusable by experienced MEV/sniping bots users. The way the protocol is designed right now is forcing the users to make multiple transactions to burn the tokens and collect the rewards they earned. Let me give some more in-depth explanation about it. 
> Providing liquidity and minting a new position, can be done trough a smart-contract or an EOA account so let's take both situations and see what is happening : 
> - if we consider a smart-contract, the flaw that I presented can be easily avoided by calling both `burnRTokens` and `transferAllTokens` in the same function, which will transfer the specific `token0` and `token1` right away, in this situation no front-run or sandwich attack happen since the funds transferred in only one transaction
> - if we consider an EOA account, especially one that interacts with the front-end of the project this is not the same, since they are forced to do at least 2 different transactions , one where he will burn their RTokens and one where he will transfer his rewards collected. That is very dangerous in general because any experienced MEV/sniping bot user can look especially for these cases and put their transactions, where they call `transferAllTokens` for themselves, right after the `burnRTokens` and before the `transferAllTokens` of the user. In UniswapV3, since kyber-swap implements a lot of logic from UniswapV3, this problem does not exist since the rewards are always stored into variables until the rightful owner calls `collect`.
> 
> As the judge said `BasePositionManager.sol` it is not intended to hold funds, but it will hold funds because of the way it is implemented, even if it is for few seconds/minutes, and because of that normal users could suffer loss of funds without having the ability to do anything, even if they call `transferAllTokens` right after burning their `RTokens`. Saying all of this I believe that the way the logic is implemented right now it is very disadvantageous for normal EOA users that are going to interact with the protocol and can lead to the loss of funds in a very easy manner since front-runs and sandwich attacks can be easily doable, especially when there is a lot to profit from.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Disagree with the escalation. Using multicall to interact with the BasePositionManager contract is part of the protocol's design. Users should execute only 1 transaction via multicall to prevent fund theft. KyberSwap has used this mechanism for a long time, so I believe this isn't an issue.

**Comment by hrishibhat** [comment]
@VagnerAndrei26 Agree with Lead judge comments. This seems to be an intended behaviour via multicall. 
Do you have additional comments?

**Comment by VagnerAndrei26** [comment]
> @VagnerAndrei26 Agree with Lead judge comments. This seems to be an intended behaviour via multicall. 
> Do you have additional comments?

Nope, I checked the live contracts and I saw that's the indended mechanic, I also agree to the judge comment, this is invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [VagnerAndrei26](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/33/#issuecomment-1728073201): rejected
