### ISSUE TITLE
radevauditor - Lack of slippage protection in `burnRTokens`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-kyber-swap-judging#75]
radevauditor

medium

# Lack of slippage protection in `burnRTokens`
## Summary
The `burnRTokens()` function in the `Pool.sol` lacks slippage protection. As a result, users might experience a discrepancy in expected versus actual tokens received due to volatile price changes.

## Vulnerability Detail
Within the `burnRTokens` function, the amount of `token0` and `token1` that a user receives upon burning rTokens is determined based on the `sqrtP` (representing `sqrtPrice`). If the `sqrtP` is susceptible to rapid fluctuations, users might not receive the amount they anticipate. Without an implemented mechanism to ensure that the difference between the expected and actual amounts (due to price fluctuations) remains within acceptable bounds, users might suffer significant financial losses.

## Impact
Without slippage protection:
1. Users might not receive the expected amount of tokens when burning rTokens.
2. Users can potentially exploit rapid price changes, leading to an imbalanced or unfair distribution of assets.
3. A loss of user trust in the protocol as unexpected financial losses can result from regular interactions.

## Code Snippet
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L259-L293

```solidity
function burnRTokens(uint256 _qty, bool isLogicalBurn)
    external
    override
    lock
    returns (uint256 qty0, uint256 qty1) {
    ...
    uint160 sqrtP = poolData.sqrtP;
    ...
    qty0 = QtyDeltaMath.getQty0FromBurnRTokens(sqrtP, deltaL);
    qty1 = QtyDeltaMath.getQty1FromBurnRTokens(sqrtP, deltaL);
    ...
    if (qty0 > 0) token0.safeTransfer(msg.sender, qty0);
    if (qty1 > 0) token1.safeTransfer(msg.sender, qty1);
    ...
}
```

## Tool used
Manual Review

## Recommendation
To protect against price slippage, consider implementing the following measures:

1. Allow users to specify a maximum acceptable slippage.
2. Compare the calculated `qty0` and `qty1` values against user-defined minimums.

**Comment by radevauditor** [comment]
Escalate

I think this is wrongly classified as invalid issue. 

Judge commented "invalid, there is already slippage check of returned amounts in BasePositionManager.burnRTokens() function"

While I understand the feedback concerning the existing slippage protection in the `BasePositionManager.burnRTokens()` function, I'd like to present a comprehensive argument detailing why the vulnerability within the `Pool` contract remains a critical concern.

1. **Direct Interaction with the Pool Contract:**
While it's true that the `BasePositionManager` has slippage protection implemented in its `burnRTokens` function, it doesn't negate the fact that the `Pool contract itself lacks this protection`.
It's imperative to consider that the Ethereum ecosystem allows for flexible interactions with smart contracts. Users, governance entities, or even third-party contracts might directly interact with the `Pool` contract, bypassing the `BasePositionManager`. The absence of slippage protection within this direct interaction poses a security risk for these actors.

3. **Holistic Security Framework:**  
In DeFi protocols, particularly those handling significant volumes and user funds, the best practice is to ensure each function and contract is secure in isolation. The presence of security checks in one part of the ecosystem doesn't automatically validate other parts, especially when they offer different interaction patterns.

4. **Trust and Protocol Reputation:**  
Even if a significant percentage of users interact using the `BasePositionManager`, the potential financial loss arising from the lack of checks in the `Pool` contract can erode trust in the protocol. Maintaining consistent security checks across all interaction points is essential for safeguarding the protocol's reputation.

5. **Real-world Interaction Patterns:**  
In practice, various strategies, bots, or advanced users might opt for direct interactions with protocols for efficiency or to implement specific strategies. Ensuring the `Pool` contract is just as secure as the `BasePositionManager` ensures these users or strategies are not vulnerable to unexpected financial discrepancies.

*There are also many examples of valid issues in past contests where the root cause is the same.*

---

I genuinely believe that the identified vulnerability in the `Pool.sol` contract's `burnRTokens()` function should be considered a **valid medium-severity issue**.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this is wrongly classified as invalid issue. 
> 
> Judge commented "invalid, there is already slippage check of returned amounts in BasePositionManager.burnRTokens() function"
> 
> While I understand the feedback concerning the existing slippage protection in the `BasePositionManager.burnRTokens()` function, I'd like to present a comprehensive argument detailing why the vulnerability within the `Pool` contract remains a critical concern.
> 
> 1. **Direct Interaction with the Pool Contract:**
> While it's true that the `BasePositionManager` has slippage protection implemented in its `burnRTokens` function, it doesn't negate the fact that the `Pool contract itself lacks this protection`.
> It's imperative to consider that the Ethereum ecosystem allows for flexible interactions with smart contracts. Users, governance entities, or even third-party contracts might directly interact with the `Pool` contract, bypassing the `BasePositionManager`. The absence of slippage protection within this direct interaction poses a security risk for these actors.
> 
> 3. **Holistic Security Framework:**  
> In DeFi protocols, particularly those handling significant volumes and user funds, the best practice is to ensure each function and contract is secure in isolation. The presence of security checks in one part of the ecosystem doesn't automatically validate other parts, especially when they offer different interaction patterns.
> 
> 4. **Trust and Protocol Reputation:**  
> Even if a significant percentage of users interact using the `BasePositionManager`, the potential financial loss arising from the lack of checks in the `Pool` contract can erode trust in the protocol. Maintaining consistent security checks across all interaction points is essential for safeguarding the protocol's reputation.
> 
> 5. **Real-world Interaction Patterns:**  
> In practice, various strategies, bots, or advanced users might opt for direct interactions with protocols for efficiency or to implement specific strategies. Ensuring the `Pool` contract is just as secure as the `BasePositionManager` ensures these users or strategies are not vulnerable to unexpected financial discrepancies.
> 
> *There are also many examples of valid issues in past contests where the root cause is the same.*
> 
> ---
> 
> I genuinely believe that the identified vulnerability in the `Pool.sol` contract's `burnRTokens()` function should be considered a **valid medium-severity issue**.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by radevauditor** [comment]
@Trumpero @sherlock-admin

**Comment by 0xdeth** [comment]
Escalate

**Comment by sherlock-admin2** [comment]
> Escalate

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by radevauditor** [comment]
Also, this issue should be discussed with the contest sponsors.

**Comment by Trumpero** [comment]
Disagree with the escalation. Users shouldn't directly execute the functions of the Pool contract; instead, they should use the PositionManager and Router contracts. The Pool contract doesn't need to have slippage control since the PositionManager and Router contracts already have it. This design is very similar to Uniswap/UniswapV3; it is a popular approach in many protocols, especially in decentralized exchanges (DEXs). Therefore, this issue should be considered invalid. 

Regarding the notes mentioned in the escalation:
1. "Direct Interaction with the Pool Contract": This scenario is considered a user's mistake since the Pool contract is not designed to be directly called by users.
2. "Holistic Security Framework": This is incorrect because KyberSwap already has slippage control and other necessary safety checks in place within its contracts.
3. "Trust and Protocol Reputation": This design doesn't cause any problems that could affect user trust. Many other protocols use a similar design.
4. "Real-world Interaction Patterns": The statement "Ensuring the Pool contract is just as secure as the BasePositionManager" doesn't make sense. Users should utilize BasePositionManager contracts, which will then call functions in the Pool contract. Therefore, having slippage checks in both contracts is redundant.

**Comment by hrishibhat** [comment]
@radevauditor
Agree with the Lead Judge's points raised above.
Do you have any additional response for the above?

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
Considering this issue a valid low based on the comments above. Also from the docs:
> Only the PositionManager holds positions in the Pool contracts, thus, users must interact with PositionManager to burn their positions.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xdeth](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/75/#issuecomment-1730972054): rejected
