### ISSUE TITLE
0x52 - Governance profits unfairly if there is a fee and pool is snip attacked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-kyber-swap-judging#89]
0x52

medium

# Governance profits unfairly if there is a fee and pool is snip attacked
## Summary

When a governance fee is set for pools, governance is minted rTokens with each swap. However if the fees are burned due to snipping attacks, governance will keep those minted rTokens and also profit from the increased valuation of the rTokens. This leads to fees being higher than they should be.

## Vulnerability Detail

[Pool.sol#L467-L472](https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L467-L472)

    if (cache.rTotalSupply != 0) {
      if (cache.governmentFee > 0) _mint(cache.feeTo, cache.governmentFee);
      if (cache.lpFee > 0) _mint(address(this), cache.lpFee);
      poolData.reinvestLLast = cache.reinvestLLast;
      poolData.feeGrowthGlobal = cache.feeGrowthGlobal;
    }

If a government fee exists on a pool then part of all rTokens will be minted to the governance specified address. However when the pool is snip attacked these corresponding shares are not burned causing effective government fees to be higher than intended. 

[AntiSnipAttackPositionManager.sol#L136-L142](https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/periphery/AntiSnipAttackPositionManager.sol#L136-L142)

    pos.rTokenOwed += additionalRTokenOwed;
    pos.feeGrowthInsideLast = feeGrowthInsideLast;
    if (feesBurnable > 0) pool.burnRTokens(feesBurnable, true);

    pos.liquidity = tmpLiquidity - params.liquidity;

    emit RemoveLiquidity(params.tokenId, params.liquidity, amount0, amount1, additionalRTokenOwed);

When rTokens are burned as a result of the snip attack safeguards the corresponding rTokens minted to the government fee recipient are not burned. Take the following example: Assume government fee = 20% and there are currently 100 rTokens. 100 tokens are minted during a snipping attack. This gives government 20 rTokens and the attacker 80. The attacker withdraws immediately, causing their 80 rTokens to be burned. After the attack the fee recipient now has 20 additional rTokens (20% fee) as well as as the 1/6th (16%) of the resulting rToken appreciation causing an effective 36% fee.

## Impact

Governance receives too many fees in the event of a snipping attack if fees are enabled

## Code Snippet

[AntiSnipAttackPositionManager.sol#L94-L143](https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/periphery/AntiSnipAttackPositionManager.sol#L94-L143)

## Tool used

Manual Review

## Recommendation

Burn the corresponding amount of rTokens from the fee recipient as well

**Comment by IAm0x52** [comment]
Escalate

I believe this has been incorrectly excluded. Having fees enabled is an expected state for the pools. 

> invalid. There is no reason to burn the government fee whenever burning rTokens for anti-snip. Additionally, there is no profit for anyone by this burning because it is logical burn (isLogicalBurn == true)

It doesn't matter if it is profitable or not for this to be attacked. Burns from anti-snip protection can easily be triggered simply by users withdrawing too soon after depositing. It is extremely likely that this will still occur. To keep proper accounting, the minted governance rTokens must be burned otherwise the fees will not be properly distributed.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe this has been incorrectly excluded. Having fees enabled is an expected state for the pools. 
> 
> > invalid. There is no reason to burn the government fee whenever burning rTokens for anti-snip. Additionally, there is no profit for anyone by this burning because it is logical burn (isLogicalBurn == true)
> 
> It doesn't matter if it is profitable or not for this to be attacked. Burns from anti-snip protection can easily be triggered simply by users withdrawing too soon after depositing. It is extremely likely that this will still occur. To keep proper accounting, the minted governance rTokens must be burned otherwise the fees will not be properly distributed.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
@IAm0x52 
Respectfully, I don't see any problem here; this doesn't cause any loss for users, and the fees are distributed correctly. If anyone executes a snip-attack, their burnable rTokens will be logically burned, and they will not receive any tokens from their fee liquidity (accumulated to `reinvestL`) in the pool. Their fees will be distributed to the other owners of rTokens based on the amount of rTokens that each one is holding.

For example, consider a scenario where only Alice and  government fee recipient hold rTokens. Alice has 80 rTokens, and the government fees amount is 20 rTokens, with `reinvestL` = 100 (the fee liquidity is distributed to the owners of rTokens). Now, Bob executes a snip-attack, which mints 80 rTokens for Bob, 20 rTokens as government fees, and increases the `reinvestL` in the Pool to 200. Bob's rTokens will be logically burned. So there will be only 80 rTokens for Alice and 40 rTokens for the government fee, while `reinvestL` remains at 200. Therefore, both Alice and the fee recipient will receive more tokens if they burn their rTokens because they will receive a larger fee liquidity (reinvestL) than before, which comes from the fee charged during Bob's swap.

**Comment by IAm0x52** [comment]
I disagree that the users have not lost fees, since the amount they receive is lower than it should be. In the scenario you've presented, the fees should be distributed 80:20 but instead they have been distributed 80:40, meaning that users have received a disproportionately lower amount of fees and governance has unfairly profited. 

Let's compare situations with and without the fee. First without the fee. In this scenario there would be no governance rTokens. Alice would have 100 rToken before the attack and the same after the attack. This would correspond to 100% of fees going to Alice as it should.

Now the scenario with fees. Governance should receive 20% of swap fees. This is the scenario presented above. Here we have a `reinvestL` of 200, Alice has 80 rTokens and governance has 40. The total swap fee is 100, which allows us to calculate what percentage of fees Alice received. Before the attack Alice is owed:

    100 * 80 / 100 = 80

After the attack, Alice is owed:

    200 * 80 / 120 = 133.33

We can than use these to figure Alice's profit:

    (133.33 - 80) / 100 = 53.3%

This means that in this scenario governance has now profited 46.67% (since only 53.3% has gone to Alice) which is much higher than the 20% it should collect. The reason for this is that their shares are improperly preserved. The 100 rTokens minted (20 to governance, 80 to attacker) are minted to correspond the fees generated by the snip attack. This means that when the snip attack protection is triggered it should burn all 100 shares associated with that attack. Instead we see that when fees are enabled only 80 of the shares are burned, instead of the full 100. This effectively means that only 80% of generated fees are redistributed instead of all of them, which leads to governance profiting unfairly.

Additionally the stated trust assumptions are that governance is not trusted to do anything but set the fee recipient and fee percentage. They are not trusted to rectify incorrect distribution of fees or to not abuse this for their own gain. The lack of trust assumptions is even more reason why I believe this should be a medium severity issue.

**Comment by Trumpero** [comment]
@IAm0x52 
I understand that the ratio of rTokens for the government fee has increased, but this doesn't result in any loss for users. As I mentioned before, `reinvestL` will still remain after logically burning rTokens for a snip-attack. It means the liquidity fee corresponding to this amount of rTokens will be used for distribution to all rToken holders, including the government fee. When users burn their rTokens after that (which is not a logical burn), they will receive more Pool tokens. In the example, the shares of rTokens changed from 80:80:40 to 80:40 after the snip-attack, but `reinvestL` (the liquidity fee) still remains at 200. Therefore, Alice will receive more tokens than before Bob quits.
https://github.com/sherlock-audit/2023-07-kyber-swap/blob/main/ks-elastic-sc/contracts/Pool.sol#L260-L293

Additionally, during a swap, a government fee is charged as 20% of minted rTokens, but it doesn't mean that the resulting profits of the government fee cannot exceed 20%. When anyone removes their liquidity before the required time (snip-attack), their remaining uncollected liquidity fee will be distributed among all shares of rTokens. Therefore, profits for all rToken holders will increase, including government fees, so I don't see any problem here.

**Comment by IAm0x52** [comment]
I believe I've already addressed all points mentioned above in my first response. 

I still hold that in the scenario discussed above only 80% (i.e. 1 - swapFee) of the swap fees generated from the snip attack will be redistributed due to governance shares being incorrectly minted which causes loss of rewards to all users since they are not receiving all the fees they should be.

As of right now I don't have any more thoughts on this and will leave this to Sherlock for final decision.

**Comment by manhlx3006** [comment]
Hi,
It is not intended to be absolutely fair. It’s mostly to make JIT attack not profitable. Also, it creates an incentive for LP to keep rtoken, where governance is also a rtoken holder (even just recently minted to governance).
It is also noted that minting rTokens and burning rTokens (as JIT) are 2 separated actions, and burning rTokens (as JIT) to benefit all rTokens holder at that time. Governance can also quickly burn/transfer rTokens right after receiving, which makes it impossible to burn rTokens from governance (which is a part of liquidation to DAO reward process)

**Comment by IAm0x52** [comment]
This isn't about being fair or unfair but that all of the fees from the attack aren't redistributed like they should be. As quoted in my previous response:

> I still hold that in the scenario discussed above only 80% (i.e. 1 - swapFee) of the swap fees generated from the snip attack will be redistributed due to governance shares being incorrectly minted which causes loss of rewards to all users since they are not receiving all the fees they should be.

Unless there are further concerns from the dev team, I think the only thing left here is for Sherlock to make the final call on severity.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering the impact of this issue a low based on the above comments and further discussion. 
In addition to the likelihood of the issue, this seems to be a design choice/limitation with it being considered an acceptable risk by the protocol.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-07-kyber-swap-judging/issues/89/#issuecomment-1730314831): rejected
